coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests-ts/**"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "jest.setup.js"
  - "jest.config.js" 