-- Auto-generated migration from backend/scripts/export_schema.ts
-- Exported at: 2026-02-21T02:45:34.066172+00:00
-- NOTE: This is a best-effort baseline for local Supabase tests.
-- Includes: 13 tables, 1 views, 35 functions, 0 triggers, 13 policies

BEGIN;

CREATE TABLE IF NOT EXISTS public."co_requisitos" (
  "id_co_requisito" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_materia" bigint NOT NULL,
  "id_materia_corequisito" bigint,
  "expressao_original" text,
  "expressao_logica" jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public."co_requisitos_backup" (
  "id_co_requisito" bigint,
  "id_materia" bigint,
  "id_materia_corequisito" bigint
);

CREATE TABLE IF NOT EXISTS public."cursos" (
  "id_curso" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "nome_curso" text,
  "tipo_curso" text
);

CREATE TABLE IF NOT EXISTS public."dados_users" (
  "id_dado_user" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "fluxograma_atual" text DEFAULT '{}'::text,
  "id_user" bigint,
  "semestre_atual" bigint
);

CREATE TABLE IF NOT EXISTS public."equivalencias" (
  "id_equivalencia" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_materia" bigint NOT NULL,
  "id_curso" bigint,
  "curriculo" text,
  "data_vigencia" date,
  "fim_vigencia" date,
  "expressao_logica" jsonb DEFAULT '{}'::jsonb,
  "expressao_original" text,
  "id_matriz" bigint
);

CREATE TABLE IF NOT EXISTS public."equivalencias_backup_temp" (
  "id_equivalencia" bigint,
  "id_materia" bigint,
  "id_curso" bigint,
  "expressao" text,
  "matriz_curricular" text,
  "curriculo" text,
  "data_vigencia" date,
  "fim_vigencia" date
);

CREATE TABLE IF NOT EXISTS public."materias" (
  "id_materia" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "nome_materia" text,
  "codigo_materia" text,
  "carga_horaria" integer,
  "ementa" text,
  "departamento" text
);

CREATE TABLE IF NOT EXISTS public."materias_backup_temp" (
  "id_materia" bigint,
  "created_at" timestamp with time zone,
  "nome_materia" text,
  "codigo_materia" text,
  "carga_horaria" bigint,
  "ementa" text,
  "departamento" text
);

CREATE TABLE IF NOT EXISTS public."materias_por_curso" (
  "id_materia_curso" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "id_materia" bigint,
  "nivel" integer,
  "id_matriz" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public."materias_por_curso_backup_temp" (
  "id_materia_curso" bigint,
  "created_at" timestamp with time zone,
  "id_materia" bigint,
  "id_curso" bigint,
  "nivel" bigint
);

CREATE TABLE IF NOT EXISTS public."matrizes" (
  "id_matriz" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_curso" bigint,
  "versao" text NOT NULL,
  "ano_vigor" text,
  "curriculo_completo" text NOT NULL,
  "ch_obrigatoria_exigida" integer,
  "ch_optativa_exigida" integer,
  "ch_complementar_exigida" integer,
  "ch_total_exigida" integer
);

CREATE TABLE IF NOT EXISTS public."pre_requisitos" (
  "id_pre_requisito" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_materia" bigint NOT NULL,
  "id_materia_requisito" bigint,
  "expressao_original" text,
  "expressao_logica" jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public."users" (
  "id_user" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "email" text,
  "nome_completo" text,
  "auth_id" uuid
);

ALTER TABLE ONLY public."co_requisitos" ADD CONSTRAINT "co_requisitos_pkey" PRIMARY KEY ("id_co_requisito");
ALTER TABLE ONLY public."cursos" ADD CONSTRAINT "cursos_pkey" PRIMARY KEY ("id_curso");
ALTER TABLE ONLY public."dados_users" ADD CONSTRAINT "dados_users_pkey" PRIMARY KEY ("id_dado_user");
ALTER TABLE ONLY public."equivalencias" ADD CONSTRAINT "equivalencias_pkey" PRIMARY KEY ("id_equivalencia");
ALTER TABLE ONLY public."materias" ADD CONSTRAINT "materias_pkey" PRIMARY KEY ("id_materia");
ALTER TABLE ONLY public."materias_por_curso" ADD CONSTRAINT "materias_por_curso_pkey" PRIMARY KEY ("id_materia_curso");
ALTER TABLE ONLY public."matrizes" ADD CONSTRAINT "matrizes_pkey" PRIMARY KEY ("id_matriz");
ALTER TABLE ONLY public."pre_requisitos" ADD CONSTRAINT "pre_requisitos_pkey" PRIMARY KEY ("id_pre_requisito");
ALTER TABLE ONLY public."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id_user");

ALTER TABLE ONLY public."co_requisitos" ADD CONSTRAINT "fk_materia_coreq" FOREIGN KEY ("id_materia") REFERENCES public."materias"("id_materia");
ALTER TABLE ONLY public."co_requisitos" ADD CONSTRAINT "fk_materia_corequisito" FOREIGN KEY ("id_materia_corequisito") REFERENCES public."materias"("id_materia");
ALTER TABLE ONLY public."dados_users" ADD CONSTRAINT "dados_users_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES public."users"("id_user");
ALTER TABLE ONLY public."equivalencias" ADD CONSTRAINT "equivalencias_id_curso_fkey" FOREIGN KEY ("id_curso") REFERENCES public."cursos"("id_curso");
ALTER TABLE ONLY public."equivalencias" ADD CONSTRAINT "equivalencias_id_materia_fkey" FOREIGN KEY ("id_materia") REFERENCES public."materias"("id_materia");
ALTER TABLE ONLY public."equivalencias" ADD CONSTRAINT "equivalencias_id_matriz_fkey" FOREIGN KEY ("id_matriz") REFERENCES public."matrizes"("id_matriz");
ALTER TABLE ONLY public."materias_por_curso" ADD CONSTRAINT "materias_por_curso_id_materia_fkey" FOREIGN KEY ("id_materia") REFERENCES public."materias"("id_materia");
ALTER TABLE ONLY public."materias_por_curso" ADD CONSTRAINT "materias_por_curso_id_matriz_fkey" FOREIGN KEY ("id_matriz") REFERENCES public."matrizes"("id_matriz");
ALTER TABLE ONLY public."matrizes" ADD CONSTRAINT "matrizes_id_curso_fkey" FOREIGN KEY ("id_curso") REFERENCES public."cursos"("id_curso");
ALTER TABLE ONLY public."pre_requisitos" ADD CONSTRAINT "fk_materia_prereq" FOREIGN KEY ("id_materia") REFERENCES public."materias"("id_materia");
ALTER TABLE ONLY public."pre_requisitos" ADD CONSTRAINT "fk_materia_requisito" FOREIGN KEY ("id_materia_requisito") REFERENCES public."materias"("id_materia");

CREATE OR REPLACE VIEW public."vw_creditos_por_matriz" AS SELECT m.id_matriz,
    m.curriculo_completo,
    c.nome_curso,
    floor(((m.ch_obrigatoria_exigida)::numeric / 15.0)) AS cred_obrigatorio_exigido,
    floor(((m.ch_optativa_exigida)::numeric / 15.0)) AS cred_optativo_exigido,
    floor(((m.ch_complementar_exigida)::numeric / 15.0)) AS cred_complementar_exigido,
    floor(((m.ch_total_exigida)::numeric / 15.0)) AS cred_total_exigido,
    floor(((COALESCE(sum(mat.carga_horaria) FILTER (WHERE (mpc.nivel > 0)), (0)::bigint))::numeric / 15.0)) AS cred_obrigatorio_grade,
    floor(((COALESCE(sum(mat.carga_horaria) FILTER (WHERE (mpc.nivel = 0)), (0)::bigint))::numeric / 15.0)) AS cred_optativo_grade
   FROM (((matrizes m
     JOIN cursos c ON ((c.id_curso = m.id_curso)))
     LEFT JOIN materias_por_curso mpc ON ((mpc.id_matriz = m.id_matriz)))
     LEFT JOIN materias mat ON ((mat.id_materia = mpc.id_materia)))
  GROUP BY m.id_matriz, m.curriculo_completo, c.nome_curso;

CREATE UNIQUE INDEX dados_users_id_user_unique ON public.dados_users USING btree (id_user);
CREATE UNIQUE INDEX materias_codigo_materia_key ON public.materias USING btree (codigo_materia);
CREATE UNIQUE INDEX unique_materia_grade_matriz ON public.materias_por_curso USING btree (id_matriz, id_materia);
CREATE UNIQUE INDEX unique_materia_na_matriz ON public.materias_por_curso USING btree (id_matriz, id_materia, nivel);
CREATE UNIQUE INDEX matrizes_curriculo_completo_key ON public.matrizes USING btree (curriculo_completo);
CREATE INDEX idx_users_auth_id ON public.users USING btree (auth_id);
CREATE UNIQUE INDEX users_auth_id_key ON public.users USING btree (auth_id);

-- =============================================================================
-- FUNCTIONS (RLS helper functions and other custom functions)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.atualizar_creditos_cursos()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    curso_row RECORD;
    total_carga_horaria INTEGER;
    total_creditos INTEGER;
BEGIN
    FOR curso_row IN SELECT id_curso FROM cursos LOOP
        -- Soma a carga horária total das matérias do curso atual
        SELECT SUM(m.carga_horaria)
        INTO total_carga_horaria
        FROM materias_por_curso mpc
        JOIN materias m ON m.id_materia = mpc.id_materia
        WHERE mpc.id_curso = curso_row.id_curso;

        -- Se o curso não tiver matérias, pula
        IF total_carga_horaria IS NULL THEN
            CONTINUE;
        END IF;

        -- Calcula os créditos inteiros (1 crédito = 15 horas)
        total_creditos := FLOOR(total_carga_horaria / 15.0);

        -- Atualiza a coluna creditos como número inteiro
        UPDATE cursos
        SET creditos = total_creditos
        WHERE id_curso = curso_row.id_curso;
    END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calcular_creditos_por_curso(id_curso_input bigint)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    total_horas INTEGER;
BEGIN
    SELECT SUM(horas)
    INTO total_horas
    FROM (
        SELECT DISTINCT
            LOWER(TRIM(m.nome_materia)) AS nome_normalizado,
            CAST(NULLIF(REGEXP_REPLACE(m.carga_horaria, '[^0-9]', '', 'g'), '') AS INTEGER) AS horas
        FROM materias m
        JOIN materias_por_curso mpc ON m.id_materia = mpc.id_materia
        WHERE mpc.id_curso = id_curso_input
          AND mpc.nivel > 0
          AND m.carga_horaria IS NOT NULL
          AND REGEXP_REPLACE(m.carga_horaria, '[^0-9]', '', 'g') <> ''
    ) AS materias_unicas;

    IF total_horas IS NULL THEN
        RETURN 0;
    END IF;

    RETURN FLOOR(total_horas / 15);
END;
$function$;

CREATE OR REPLACE FUNCTION public.export_schema()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN jsonb_build_object(
        'exported_at', NOW(),
        'postgres_version', version(),
        
        -- TABLES WITH DETAILED COLUMNS
        'tables', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'table_name', t.table_name,
                'table_type', t.table_type,
                'table_comment', obj_description(pc.oid, 'pg_class'),
                'columns', (
                    SELECT COALESCE(jsonb_agg(jsonb_build_object(
                        'column_name', c.column_name,
                        'data_type', c.data_type,
                        'udt_name', c.udt_name,
                        'is_nullable', c.is_nullable,
                        'column_default', c.column_default,
                        'is_identity', c.is_identity,
                        'identity_generation', c.identity_generation,
                        'ordinal_position', c.ordinal_position,
                        'character_maximum_length', c.character_maximum_length,
                        'numeric_precision', c.numeric_precision,
                        'numeric_scale', c.numeric_scale,
                        'datetime_precision', c.datetime_precision,
                        'is_updatable', c.is_updatable,
                        'column_comment', col_description(pc.oid, c.ordinal_position)
                    ) ORDER BY c.ordinal_position), '[]'::jsonb)
                    FROM information_schema.columns c 
                    WHERE c.table_name = t.table_name 
                    AND c.table_schema = 'public'
                )
            ) ORDER BY t.table_name), '[]'::jsonb)
            FROM information_schema.tables t
            JOIN pg_class pc ON pc.relname = t.table_name AND pc.relnamespace = 'public'::regnamespace
            WHERE t.table_schema = 'public'
            AND t.table_type = 'BASE TABLE'
        ),
        
        -- VIEWS WITH DEFINITIONS
        'views', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'view_name', table_name,
                'view_definition', view_definition,
                'is_updatable', is_updatable,
                'is_insertable_into', is_insertable_into
            ) ORDER BY table_name), '[]'::jsonb)
            FROM information_schema.views
            WHERE table_schema = 'public'
        ),

        -- MATERIALIZED VIEWS WITH DEFINITIONS
        'materialized_views', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'view_name', matviewname,
                'view_definition', definition,
                'is_populated', ispopulated
            ) ORDER BY matviewname), '[]'::jsonb)
            FROM pg_matviews
            WHERE schemaname = 'public'
        ),
        
        -- FUNCTIONS AND PROCEDURES (with full definitions and source code)
        'functions', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'function_name', p.proname,
                'function_oid', p.oid::bigint,
                'return_type', pg_get_function_result(p.oid),
                'arguments', pg_get_function_arguments(p.oid),
                'argument_types', pg_get_function_identity_arguments(p.oid),
                'function_type', CASE 
                    WHEN p.prokind = 'f' THEN 'function'
                    WHEN p.prokind = 'p' THEN 'procedure'
                    WHEN p.prokind = 'a' THEN 'aggregate'
                    WHEN p.prokind = 'w' THEN 'window'
                    ELSE 'unknown'
                END,
                'volatility', CASE p.provolatile
                    WHEN 'i' THEN 'IMMUTABLE'
                    WHEN 's' THEN 'STABLE'
                    WHEN 'v' THEN 'VOLATILE'
                END,
                'parallel_safety', CASE p.proparallel
                    WHEN 's' THEN 'SAFE'
                    WHEN 'r' THEN 'RESTRICTED'
                    WHEN 'u' THEN 'UNSAFE'
                END,
                'security_definer', p.prosecdef,
                'strict', p.proisstrict,
                'returns_set', p.proretset,
                'language', l.lanname,
                'source_code', p.prosrc,
                'definition', pg_get_functiondef(p.oid),
                'config', p.proconfig,
                'comment', obj_description(p.oid, 'pg_proc')
            ) ORDER BY p.proname), '[]'::jsonb)
            FROM pg_proc p
            JOIN pg_namespace n ON p.pronamespace = n.oid
            JOIN pg_language l ON p.prolang = l.oid
            WHERE n.nspname = 'public'
            AND p.prokind IN ('f', 'p')
        ),
        
        -- TRIGGERS WITH FULL DEFINITIONS (including the trigger function definition)
        -- Only triggers on PUBLIC schema tables
        'triggers', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'trigger_name', tg.tgname,
                'table_name', tab.relname,
                'table_schema', ns.nspname,
                'trigger_type', CASE 
                    WHEN tg.tgtype & 2 = 2 THEN 'BEFORE'
                    WHEN tg.tgtype & 64 = 64 THEN 'INSTEAD OF'
                    ELSE 'AFTER'
                END,
                'trigger_events', concat_ws(' OR ',
                    CASE WHEN tg.tgtype & 4 = 4 THEN 'INSERT' END,
                    CASE WHEN tg.tgtype & 8 = 8 THEN 'DELETE' END,
                    CASE WHEN tg.tgtype & 16 = 16 THEN 'UPDATE' END,
                    CASE WHEN tg.tgtype & 32 = 32 THEN 'TRUNCATE' END
                ),
                'for_each', CASE WHEN tg.tgtype & 1 = 1 THEN 'ROW' ELSE 'STATEMENT' END,
                'trigger_function_name', p.proname,
                'trigger_function_schema', fn.nspname,
                'trigger_function_definition', pg_get_functiondef(p.oid),
                'trigger_function_source', p.prosrc,
                'is_enabled', CASE tg.tgenabled
                    WHEN 'O' THEN true
                    WHEN 'D' THEN false
                    WHEN 'R' THEN true  -- replica
                    WHEN 'A' THEN true  -- always
                    ELSE true
                END,
                'trigger_definition', pg_get_triggerdef(tg.oid),
                -- NOTE: tg.tgqual can reference both OLD and NEW, which makes pg_get_expr error
                -- ("expression contains variables of more than one relation"). We extract WHEN()
                -- from the full trigger definition instead (best-effort).
                'condition', substring(pg_get_triggerdef(tg.oid) from 'WHEN \\((.*)\\) EXECUTE')
            ) ORDER BY tab.relname, tg.tgname), '[]'::jsonb)
            FROM pg_trigger tg
            JOIN pg_class tab ON tg.tgrelid = tab.oid
            JOIN pg_namespace ns ON tab.relnamespace = ns.oid
            JOIN pg_proc p ON tg.tgfoid = p.oid
            JOIN pg_namespace fn ON p.pronamespace = fn.oid
            WHERE ns.nspname = 'public'
            AND NOT tg.tgisinternal  -- exclude system triggers
        ),
        
        -- TRIGGERS ON auth.users (critical for signup flows)
        -- These triggers fire when users sign up and typically create profiles
        'auth_triggers', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'trigger_name', tg.tgname,
                'table_name', tab.relname,
                'table_schema', ns.nspname,
                'trigger_type', CASE 
                    WHEN tg.tgtype & 2 = 2 THEN 'BEFORE'
                    WHEN tg.tgtype & 64 = 64 THEN 'INSTEAD OF'
                    ELSE 'AFTER'
                END,
                'trigger_events', concat_ws(' OR ',
                    CASE WHEN tg.tgtype & 4 = 4 THEN 'INSERT' END,
                    CASE WHEN tg.tgtype & 8 = 8 THEN 'DELETE' END,
                    CASE WHEN tg.tgtype & 16 = 16 THEN 'UPDATE' END,
                    CASE WHEN tg.tgtype & 32 = 32 THEN 'TRUNCATE' END
                ),
                'for_each', CASE WHEN tg.tgtype & 1 = 1 THEN 'ROW' ELSE 'STATEMENT' END,
                'trigger_function_name', p.proname,
                'trigger_function_schema', fn.nspname,
                'trigger_function_definition', CASE 
                    WHEN fn.nspname = 'public' THEN pg_get_functiondef(p.oid)
                    ELSE NULL  -- Can't always get definition for non-public functions
                END,
                'trigger_function_source', CASE 
                    WHEN fn.nspname = 'public' THEN p.prosrc
                    ELSE NULL
                END,
                'is_enabled', CASE tg.tgenabled
                    WHEN 'O' THEN true
                    WHEN 'D' THEN false
                    WHEN 'R' THEN true
                    WHEN 'A' THEN true
                    ELSE true
                END,
                'trigger_definition', pg_get_triggerdef(tg.oid)
            ) ORDER BY tg.tgname), '[]'::jsonb)
            FROM pg_trigger tg
            JOIN pg_class tab ON tg.tgrelid = tab.oid
            JOIN pg_namespace ns ON tab.relnamespace = ns.oid
            JOIN pg_proc p ON tg.tgfoid = p.oid
            JOIN pg_namespace fn ON p.pronamespace = fn.oid
            WHERE ns.nspname = 'auth'
            AND tab.relname = 'users'
            AND NOT tg.tgisinternal
        ),
        
        -- FOREIGN KEYS (public schema only)
        'foreign_keys', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'constraint_name', tc.constraint_name,
                'table_name', tc.table_name,
                'column_name', kcu.column_name,
                'foreign_table_name', ccu.table_name,
                'foreign_column_name', ccu.column_name,
                'update_rule', rc.update_rule,
                'delete_rule', rc.delete_rule,
                'match_option', rc.match_option
            ) ORDER BY tc.table_name, tc.constraint_name), '[]'::jsonb)
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
                ON tc.constraint_name = kcu.constraint_name
                AND tc.table_schema = kcu.table_schema
            JOIN information_schema.constraint_column_usage ccu
                ON ccu.constraint_name = tc.constraint_name
                AND ccu.table_schema = tc.table_schema
            JOIN information_schema.referential_constraints rc
                ON rc.constraint_name = tc.constraint_name
                AND rc.constraint_schema = tc.table_schema
            WHERE tc.constraint_type = 'FOREIGN KEY'
            AND tc.table_schema = 'public'
        ),
        
        -- FOREIGN KEYS REFERENCING auth.users
        -- These are critical for user profile tables that link to auth.users
        'auth_foreign_keys', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'constraint_name', con.conname,
                'table_schema', nsp.nspname,
                'table_name', rel.relname,
                'column_name', att.attname,
                'foreign_table_schema', fnsp.nspname,
                'foreign_table_name', frel.relname,
                'foreign_column_name', fatt.attname,
                'on_delete', CASE con.confdeltype
                    WHEN 'a' THEN 'NO ACTION'
                    WHEN 'r' THEN 'RESTRICT'
                    WHEN 'c' THEN 'CASCADE'
                    WHEN 'n' THEN 'SET NULL'
                    WHEN 'd' THEN 'SET DEFAULT'
                END,
                'on_update', CASE con.confupdtype
                    WHEN 'a' THEN 'NO ACTION'
                    WHEN 'r' THEN 'RESTRICT'
                    WHEN 'c' THEN 'CASCADE'
                    WHEN 'n' THEN 'SET NULL'
                    WHEN 'd' THEN 'SET DEFAULT'
                END
            ) ORDER BY rel.relname), '[]'::jsonb)
            FROM pg_constraint con
            JOIN pg_class rel ON con.conrelid = rel.oid
            JOIN pg_namespace nsp ON rel.relnamespace = nsp.oid
            JOIN pg_class frel ON con.confrelid = frel.oid
            JOIN pg_namespace fnsp ON frel.relnamespace = fnsp.oid
            JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
            JOIN pg_attribute fatt ON fatt.attrelid = frel.oid AND fatt.attnum = ANY(con.confkey)
            WHERE con.contype = 'f'
            AND fnsp.nspname = 'auth'
            AND frel.relname = 'users'
        ),
        
        -- PRIMARY KEYS
        'primary_keys', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'constraint_name', tc.constraint_name,
                'table_name', tc.table_name,
                'column_name', kcu.column_name,
                'ordinal_position', kcu.ordinal_position
            ) ORDER BY tc.table_name, kcu.ordinal_position), '[]'::jsonb)
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
                ON tc.constraint_name = kcu.constraint_name
                AND tc.table_schema = kcu.table_schema
            WHERE tc.constraint_type = 'PRIMARY KEY'
            AND tc.table_schema = 'public'
        ),
        
        -- UNIQUE CONSTRAINTS
        'unique_constraints', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'constraint_name', tc.constraint_name,
                'table_name', tc.table_name,
                'column_name', kcu.column_name,
                'ordinal_position', kcu.ordinal_position
            ) ORDER BY tc.table_name, tc.constraint_name, kcu.ordinal_position), '[]'::jsonb)
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
                ON tc.constraint_name = kcu.constraint_name
                AND tc.table_schema = kcu.table_schema
            WHERE tc.constraint_type = 'UNIQUE'
            AND tc.table_schema = 'public'
        ),
        
        -- CHECK CONSTRAINTS
        'check_constraints', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'constraint_name', cc.constraint_name,
                'table_name', tc.table_name,
                'check_clause', cc.check_clause
            ) ORDER BY tc.table_name, cc.constraint_name), '[]'::jsonb)
            FROM information_schema.check_constraints cc
            JOIN information_schema.table_constraints tc
                ON cc.constraint_name = tc.constraint_name
                AND cc.constraint_schema = tc.table_schema
            WHERE cc.constraint_schema = 'public'
            AND tc.constraint_type = 'CHECK'
        ),
        
        -- INDEXES (with full definition)
        'indexes', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'index_name', indexname,
                'table_name', tablename,
                'index_definition', indexdef
            ) ORDER BY tablename, indexname), '[]'::jsonb)
            FROM pg_indexes
            WHERE schemaname = 'public'
        ),
        
        -- SEQUENCES (with current values and settings)
        'sequences', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'sequence_name', sq.relname,
                'data_type', sq.seqtypid::regtype::text,
                'start_value', sq.seqstart,
                'min_value', sq.seqmin,
                'max_value', sq.seqmax,
                'increment_by', sq.seqincrement,
                'cycle', sq.seqcycle,
                'cache_size', sq.seqcache,
                'owned_by', sq.owned_by
            ) ORDER BY sq.relname), '[]'::jsonb)
            FROM (
                SELECT 
                    s.relname,
                    s.oid as seq_oid,
                    seq.seqtypid,
                    seq.seqstart,
                    seq.seqmin,
                    seq.seqmax,
                    seq.seqincrement,
                    seq.seqcycle,
                    seq.seqcache,
                    (
                        SELECT a.attrelid::regclass || '.' || a.attname
                        FROM pg_depend d
                        JOIN pg_attribute a ON d.refobjid = a.attrelid AND d.refobjsubid = a.attnum
                        WHERE d.objid = s.oid AND d.deptype = 'a'
                        LIMIT 1
                    ) as owned_by
                FROM pg_class s
                JOIN pg_sequence seq ON s.oid = seq.seqrelid
                JOIN pg_namespace n ON s.relnamespace = n.oid
                WHERE n.nspname = 'public'
                AND s.relkind = 'S'
            ) sq
        ),
        
        -- RLS POLICIES (with roles)
        'policies', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'policy_name', pol.polname,
                'table_name', tab.relname,
                'command', CASE pol.polcmd 
                    WHEN 'r' THEN 'SELECT'
                    WHEN 'a' THEN 'INSERT'
                    WHEN 'w' THEN 'UPDATE'
                    WHEN 'd' THEN 'DELETE'
                    WHEN '*' THEN 'ALL'
                END,
                'permissive', CASE pol.polpermissive 
                    WHEN true THEN 'PERMISSIVE'
                    ELSE 'RESTRICTIVE'
                END,
                'roles', COALESCE(
                    (SELECT array_agg(r.rolname) FROM pg_roles r WHERE r.oid = ANY(pol.polroles)),
                    ARRAY['public']
                ),
                'using_expression', pg_get_expr(pol.polqual, pol.polrelid),
                'with_check_expression', pg_get_expr(pol.polwithcheck, pol.polrelid)
            ) ORDER BY tab.relname, pol.polname), '[]'::jsonb)
            FROM pg_policy pol
            JOIN pg_class tab ON pol.polrelid = tab.oid
            JOIN pg_namespace nsp ON tab.relnamespace = nsp.oid
            WHERE nsp.nspname = 'public'
        ),
        
        -- ENUMS
        'enums', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'enum_name', t.typname,
                'enum_values', (
                    SELECT array_agg(e.enumlabel ORDER BY e.enumsortorder)
                    FROM pg_enum e
                    WHERE e.enumtypid = t.oid
                )
            ) ORDER BY t.typname), '[]'::jsonb)
            FROM pg_type t
            JOIN pg_namespace n ON t.typnamespace = n.oid
            WHERE n.nspname = 'public'
            AND t.typtype = 'e'
        ),
        
        -- EXTENSIONS
        'extensions', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'extension_name', e.extname,
                'schema', n.nspname,
                'version', e.extversion,
                'relocatable', e.extrelocatable
            ) ORDER BY e.extname), '[]'::jsonb)
            FROM pg_extension e
            JOIN pg_namespace n ON e.extnamespace = n.oid
        ),
        
        -- TABLE STATS (row counts and sizes)
        'table_stats', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'table_name', relname,
                'estimated_rows', reltuples::bigint,
                'total_size_bytes', pg_total_relation_size(oid),
                'table_size_bytes', pg_table_size(oid),
                'indexes_size_bytes', pg_indexes_size(oid)
            ) ORDER BY relname), '[]'::jsonb)
            FROM pg_class
            WHERE relnamespace = 'public'::regnamespace
            AND relkind = 'r'
        ),
        
        -- RLS ENABLED TABLES
        'rls_enabled_tables', (
            SELECT COALESCE(jsonb_agg(relname ORDER BY relname), '[]'::jsonb)
            FROM pg_class c
            JOIN pg_namespace n ON c.relnamespace = n.oid
            WHERE n.nspname = 'public'
            AND c.relkind = 'r'
            AND c.relrowsecurity = true
        )
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.gin_extract_query_trgm(text, internal, smallint, internal, internal, internal, internal)
 RETURNS internal
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gin_extract_query_trgm$function$;

CREATE OR REPLACE FUNCTION public.gin_extract_value_trgm(text, internal)
 RETURNS internal
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gin_extract_value_trgm$function$;

CREATE OR REPLACE FUNCTION public.gin_trgm_consistent(internal, smallint, text, integer, internal, internal, internal, internal)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gin_trgm_consistent$function$;

CREATE OR REPLACE FUNCTION public.gin_trgm_triconsistent(internal, smallint, text, integer, internal, internal, internal)
 RETURNS "char"
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gin_trgm_triconsistent$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_compress(internal)
 RETURNS internal
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_compress$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_consistent(internal, text, smallint, oid, internal)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_consistent$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_decompress(internal)
 RETURNS internal
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_decompress$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_distance(internal, text, smallint, oid, internal)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_distance$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_in(cstring)
 RETURNS gtrgm
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_in$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_options(internal)
 RETURNS void
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE
AS '$libdir/pg_trgm', $function$gtrgm_options$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_out(gtrgm)
 RETURNS cstring
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_out$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_penalty(internal, internal, internal)
 RETURNS internal
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_penalty$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_picksplit(internal, internal)
 RETURNS internal
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_picksplit$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_same(gtrgm, gtrgm, internal)
 RETURNS internal
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_same$function$;

CREATE OR REPLACE FUNCTION public.gtrgm_union(internal, internal)
 RETURNS gtrgm
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$gtrgm_union$function$;

CREATE OR REPLACE FUNCTION public.set_limit(real)
 RETURNS real
 LANGUAGE c
 STRICT
AS '$libdir/pg_trgm', $function$set_limit$function$;

CREATE OR REPLACE FUNCTION public.show_limit()
 RETURNS real
 LANGUAGE c
 STABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$show_limit$function$;

CREATE OR REPLACE FUNCTION public.show_trgm(text)
 RETURNS text[]
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$show_trgm$function$;

CREATE OR REPLACE FUNCTION public.similarity(text, text)
 RETURNS real
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$similarity$function$;

CREATE OR REPLACE FUNCTION public.similarity_dist(text, text)
 RETURNS real
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$similarity_dist$function$;

CREATE OR REPLACE FUNCTION public.similarity_op(text, text)
 RETURNS boolean
 LANGUAGE c
 STABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$similarity_op$function$;

CREATE OR REPLACE FUNCTION public.strict_word_similarity(text, text)
 RETURNS real
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$strict_word_similarity$function$;

CREATE OR REPLACE FUNCTION public.strict_word_similarity_commutator_op(text, text)
 RETURNS boolean
 LANGUAGE c
 STABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$strict_word_similarity_commutator_op$function$;

CREATE OR REPLACE FUNCTION public.strict_word_similarity_dist_commutator_op(text, text)
 RETURNS real
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$strict_word_similarity_dist_commutator_op$function$;

CREATE OR REPLACE FUNCTION public.strict_word_similarity_dist_op(text, text)
 RETURNS real
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$strict_word_similarity_dist_op$function$;

CREATE OR REPLACE FUNCTION public.strict_word_similarity_op(text, text)
 RETURNS boolean
 LANGUAGE c
 STABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$strict_word_similarity_op$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.word_similarity(text, text)
 RETURNS real
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$word_similarity$function$;

CREATE OR REPLACE FUNCTION public.word_similarity_commutator_op(text, text)
 RETURNS boolean
 LANGUAGE c
 STABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$word_similarity_commutator_op$function$;

CREATE OR REPLACE FUNCTION public.word_similarity_dist_commutator_op(text, text)
 RETURNS real
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$word_similarity_dist_commutator_op$function$;

CREATE OR REPLACE FUNCTION public.word_similarity_dist_op(text, text)
 RETURNS real
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$word_similarity_dist_op$function$;

CREATE OR REPLACE FUNCTION public.word_similarity_op(text, text)
 RETURNS boolean
 LANGUAGE c
 STABLE PARALLEL SAFE STRICT
AS '$libdir/pg_trgm', $function$word_similarity_op$function$;

ALTER TABLE public."co_requisitos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cursos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."dados_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."equivalencias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."materias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."materias_por_curso" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."pre_requisitos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."users" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "co_requisitos_select_public" ON public."co_requisitos" AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "cursos_select_public" ON public."cursos" AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "dados_users_delete_own" ON public."dados_users" AS PERMISSIVE FOR DELETE TO authenticated USING ((id_user IN ( SELECT users.id_user
   FROM users
  WHERE (users.auth_id = auth.uid()))));
CREATE POLICY "dados_users_insert_own" ON public."dados_users" AS PERMISSIVE FOR INSERT TO authenticated USING (true) WITH CHECK ((id_user IN ( SELECT users.id_user
   FROM users
  WHERE (users.auth_id = auth.uid()))));
CREATE POLICY "dados_users_select_own" ON public."dados_users" AS PERMISSIVE FOR SELECT TO authenticated USING ((id_user IN ( SELECT users.id_user
   FROM users
  WHERE (users.auth_id = auth.uid()))));
CREATE POLICY "dados_users_update_own" ON public."dados_users" AS PERMISSIVE FOR UPDATE TO authenticated USING ((id_user IN ( SELECT users.id_user
   FROM users
  WHERE (users.auth_id = auth.uid())))) WITH CHECK ((id_user IN ( SELECT users.id_user
   FROM users
  WHERE (users.auth_id = auth.uid()))));
CREATE POLICY "equivalencias_select_public" ON public."equivalencias" AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "materias_select_public" ON public."materias" AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "materias_por_curso_select_public" ON public."materias_por_curso" AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "pre_requisitos_select_public" ON public."pre_requisitos" AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "users_insert_own" ON public."users" AS PERMISSIVE FOR INSERT TO authenticated USING (true) WITH CHECK ((auth_id = auth.uid()));
CREATE POLICY "users_select_own" ON public."users" AS PERMISSIVE FOR SELECT TO authenticated USING ((auth_id = auth.uid()));
CREATE POLICY "users_update_own" ON public."users" AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth_id = auth.uid())) WITH CHECK ((auth_id = auth.uid()));

COMMIT;
