-- Preferência de turno/professor por matéria, confirmada pelo aluno no chat da
-- Darcy (Montador de Grade) — banner "Aceitar"/"Manter grade anterior".
-- Rodar uma vez no SQL editor do Supabase. Sem FK pra "users": o resto do
-- schema também não usa (ver latest_init_from_export.sql), SERVICE_ROLE_KEY
-- bypassa RLS em todas as operações do backend.

create table if not exists public.preferencias_grade (
  id_preferencia bigint generated by default as identity primary key,
  id_user bigint not null,
  codigo_materia text not null,
  turnos text[] not null default '{}',
  docente text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (id_user, codigo_materia)
);

create index if not exists preferencias_grade_id_user_idx on public.preferencias_grade (id_user);
