-- Alerta de saldo da IA (Maritaca) no dashboard admin (30/09/2026).
-- Aplicar manualmente no SQL Editor do Supabase DEPOIS de:
--   * 20260929_darcy_cota.sql (ai_usage_log.user_id/pergunta_id,
--     darcy_dia_brasilia);
--   * 20260929b_dashboard_rastreabilidade.sql (o custo passa a contar o que
--     o modelo cobrou nas falhas — o saldo estimado desconta o mesmo gasto).
-- Aplicar ANTES do deploy do backend que grava ai_usage_log.erro_codigo (sem a
-- coluna, o backend refaz o insert sem ela e o evento "sem créditos" se perde,
-- mas o custo continua registrado).
-- Idempotente: pode ser reaplicada.
--
-- Por quê: a Maritaca não tem API pública de saldo (só o painel
-- plataforma.maritaca.ai). O admin informa o saldo que vê lá; o banco
-- desconta o custo medido em ai_usage_log × ai_pricing desde esse registro.
--
-- O que cria/altera:
--   1. ai_usage_log.erro_codigo: marcador da falha. 'ai_sem_creditos' = a
--      Maritaca respondeu 403 insufficient_funds (backend: isMaritacaSemCreditos
--      em qualquer rota de IA; a linha tem success=false).
--   2. ai_saldo_registros: 'saldo_atual' (redefine a base) e 'recarga' (soma à
--      base vigente), com quem e quando registrou.
--   3. ai_saldo_config (uma linha só): modelos cobrados do crédito da Maritaca
--      e limiares dos alertas. O admin muda sem deploy, no SQL Editor:
--        UPDATE public.ai_saldo_config SET atencao_reais = 50 WHERE id;
--        UPDATE public.ai_saldo_config
--           SET modelos_maritaca = array_append(modelos_maritaca, 'sabia-5') WHERE id;
--   4. registrar_ai_saldo(tipo, valor, observacao) e get_ai_saldo_status():
--      só com has_admin_scope('dashboard') — o mesmo escopo do dashboard.
--
-- Cálculo (get_ai_saldo_status → ai_saldo_status_em):
--   base            = último 'saldo_atual' + 'recarga's registradas depois dele
--   custo           = Σ custo das linhas de ai_usage_log com model em
--                     modelos_maritaca e created_at >= registro do último
--                     'saldo_atual' (inclui success=false: o modelo cobrou).
--                     Gemini (embeddings) e RAGFlow não saem do crédito da
--                     Maritaca e ficam de fora.
--   saldo_estimado  = base − custo. Preço cheio de ai_pricing: descontos da
--                     Maritaca (noturno, cache) não entram — o real tende a ser
--                     um pouco maior.
--   previsão        = custo dos modelos Maritaca nos últimos 7 dias COMPLETOS
--                     de Brasília (ontem e os 6 antes; hoje fica de fora, porque
--                     o dia incompleto puxaria a média para baixo e inflaria os
--                     dias restantes) ÷ dias considerados. Com menos de 7 dias
--                     completos de log, divide pelos disponíveis e marca parcial
--                     (o 1º dia de log conta inteiro, mesmo que tenha começado
--                     no meio). Se o log só tem o dia de hoje, projeta o gasto
--                     de hoje para 24 h pelas horas já passadas (mínimo 1 h, para
--                     a madrugada não virar extrapolação de minutos) e devolve
--                     previsao.horas_hoje. Média 0 (sem gasto) → sem previsão.
--   alertas (ordem de prioridade):
--     sem_creditos   erro_codigo='ai_sem_creditos' nas últimas sem_creditos_horas
--     urgente        saldo < urgente_reais  ou  dias restantes < urgente_dias
--     atencao        saldo < atencao_reais  ou  dias restantes < atencao_dias
--     desatualizado  nenhum registro, ou o último tem > desatualizado_dias
--
-- Leitura/escrita das tabelas novas: só pelas funções SECURITY DEFINER.
-- Nenhum dado pessoal novo além do auth_id do admin que registrou.
--
-- REVERSÃO (rodar numa transação):
--   DROP FUNCTION IF EXISTS public.registrar_ai_saldo(text, numeric, text);
--   DROP FUNCTION IF EXISTS public.get_ai_saldo_status();
--   DROP FUNCTION IF EXISTS public.ai_saldo_status_em(timestamptz);
--   DROP TABLE IF EXISTS public.ai_saldo_config;
--   DROP TABLE IF EXISTS public.ai_saldo_registros;
--   DROP INDEX IF EXISTS public.idx_ai_usage_erro_codigo;
--   ALTER TABLE public.ai_usage_log DROP COLUMN IF EXISTS erro_codigo;

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Marcador de erro no log de IA
-- ---------------------------------------------------------------------------

ALTER TABLE public.ai_usage_log ADD COLUMN IF NOT EXISTS erro_codigo text;

CREATE INDEX IF NOT EXISTS idx_ai_usage_erro_codigo
  ON public.ai_usage_log (erro_codigo, created_at) WHERE erro_codigo IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 2. Registros de saldo
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_saldo_registros (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo           text NOT NULL CHECK (tipo IN ('saldo_atual', 'recarga')),
  valor          numeric(12, 2) NOT NULL,
  registrado_em  timestamptz NOT NULL DEFAULT now(),
  registrado_por uuid,
  observacao     text CHECK (observacao IS NULL OR char_length(observacao) <= 500),
  CONSTRAINT ai_saldo_valor_ck CHECK (
    (tipo = 'saldo_atual' AND valor >= 0) OR (tipo = 'recarga' AND valor > 0)
  )
);

CREATE INDEX IF NOT EXISTS idx_ai_saldo_registros_em
  ON public.ai_saldo_registros (registrado_em DESC, id DESC);

-- ---------------------------------------------------------------------------
-- 3. Configuração (uma linha)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ai_saldo_config (
  id                   boolean PRIMARY KEY DEFAULT true CHECK (id),
  -- Modelos cobrados do crédito da Maritaca (nomes como em ai_usage_log.model).
  modelos_maritaca     text[] NOT NULL
                       DEFAULT ARRAY['sabia-4', 'sabiazinho-4', 'sabia-3', 'sabia-3.1', 'sabiazinho-3'],
  urgente_reais        numeric NOT NULL DEFAULT 10 CHECK (urgente_reais >= 0),
  urgente_dias         numeric NOT NULL DEFAULT 5 CHECK (urgente_dias >= 0),
  atencao_reais        numeric NOT NULL DEFAULT 30 CHECK (atencao_reais >= 0),
  atencao_dias         numeric NOT NULL DEFAULT 14 CHECK (atencao_dias >= 0),
  desatualizado_dias   integer NOT NULL DEFAULT 15 CHECK (desatualizado_dias > 0),
  sem_creditos_horas   integer NOT NULL DEFAULT 24 CHECK (sem_creditos_horas > 0),
  janela_previsao_dias integer NOT NULL DEFAULT 7 CHECK (janela_previsao_dias BETWEEN 1 AND 90),
  atualizado_em        timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.ai_saldo_config (id) VALUES (true) ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. RLS e grants: nada direto para anon/authenticated
-- ---------------------------------------------------------------------------

ALTER TABLE public.ai_saldo_registros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_saldo_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_saldo_registros FROM anon, authenticated;
REVOKE ALL ON public.ai_saldo_config FROM anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Status (cálculo com o instante como parâmetro, para teste determinístico)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.ai_saldo_status_em(p_agora timestamptz)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  c                 public.ai_saldo_config;
  v_moeda           text;
  v_base            public.ai_saldo_registros;
  v_ultimo          public.ai_saldo_registros;
  v_ultimo_nome     text;
  v_ultimo_email    text;
  v_recargas        numeric := 0;
  v_n_recargas      integer := 0;
  v_saldo_base      numeric;
  v_custo           numeric := 0;
  v_saldo           numeric;
  v_sem_preco       jsonb := '[]'::jsonb;
  v_hoje            date := (p_agora AT TIME ZONE 'America/Sao_Paulo')::date;
  v_hoje_ts         timestamptz;
  v_inicio_janela   date;
  v_primeiro_dia    date;
  v_dias_completos  integer;
  v_horas_hoje      numeric;
  v_dias            numeric;
  v_custo_janela    numeric;
  v_media           numeric;
  v_dias_restantes  numeric;
  v_ult_sem_cred    timestamptz;
  v_n_sem_cred      integer;
  v_dias_desde      numeric;
  v_alertas         text[] := ARRAY[]::text[];
BEGIN
  SELECT * INTO c FROM public.ai_saldo_config WHERE id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'ai_saldo_config sem linha: reaplique 20260930_ai_saldo.sql';
  END IF;

  SELECT COALESCE(max(currency), 'BRL') INTO v_moeda FROM public.ai_pricing;

  -- Base: último saldo informado + recargas registradas depois dele.
  SELECT * INTO v_base FROM public.ai_saldo_registros r
   WHERE r.tipo = 'saldo_atual' AND r.registrado_em <= p_agora
   ORDER BY r.registrado_em DESC, r.id DESC LIMIT 1;

  SELECT * INTO v_ultimo FROM public.ai_saldo_registros r
   WHERE r.registrado_em <= p_agora
   ORDER BY r.registrado_em DESC, r.id DESC LIMIT 1;

  IF v_ultimo.id IS NOT NULL THEN
    SELECT u.nome_completo, u.email INTO v_ultimo_nome, v_ultimo_email
      FROM public.users u WHERE u.auth_id = v_ultimo.registrado_por
     LIMIT 1;
    v_dias_desde := round((EXTRACT(EPOCH FROM (p_agora - v_ultimo.registrado_em)) / 86400.0)::numeric, 1);
  END IF;

  IF v_base.id IS NOT NULL THEN
    SELECT COALESCE(sum(r.valor), 0), count(*) INTO v_recargas, v_n_recargas
      FROM public.ai_saldo_registros r
     WHERE r.tipo = 'recarga' AND r.registrado_em <= p_agora
       AND (r.registrado_em, r.id) > (v_base.registrado_em, v_base.id);

    SELECT COALESCE(sum(
             (l.prompt_tokens / 1000.0) * COALESCE(p.input_per_1k, 0)
           + (l.completion_tokens / 1000.0) * COALESCE(p.output_per_1k, 0)), 0),
           COALESCE(jsonb_agg(DISTINCT l.model) FILTER (
             WHERE p.model IS NULL OR (p.input_per_1k = 0 AND p.output_per_1k = 0)), '[]'::jsonb)
      INTO v_custo, v_sem_preco
      FROM public.ai_usage_log l
      LEFT JOIN public.ai_pricing p ON p.model = l.model
     WHERE l.model = ANY (c.modelos_maritaca)
       AND l.created_at >= v_base.registrado_em
       AND l.created_at <= p_agora;

    v_saldo_base := v_base.valor + v_recargas;
    v_saldo := v_saldo_base - v_custo;
  END IF;

  -- Previsão: dias completos de Brasília [hoje - janela, hoje - 1]; só hoje,
  -- proporcional às horas passadas, quando o log ainda não tem dia completo.
  v_hoje_ts := v_hoje::timestamp AT TIME ZONE 'America/Sao_Paulo';

  SELECT min((l.created_at AT TIME ZONE 'America/Sao_Paulo')::date) INTO v_primeiro_dia
    FROM public.ai_usage_log l
   WHERE l.model = ANY (c.modelos_maritaca) AND l.created_at <= p_agora;

  IF v_primeiro_dia IS NOT NULL THEN
    IF v_primeiro_dia < v_hoje THEN
      v_inicio_janela  := GREATEST(v_primeiro_dia, v_hoje - c.janela_previsao_dias);
      v_dias_completos := v_hoje - v_inicio_janela;
      v_dias           := v_dias_completos;
    ELSE
      v_inicio_janela  := v_hoje;
      v_dias_completos := 0;
      v_horas_hoje     := GREATEST(EXTRACT(EPOCH FROM (p_agora - v_hoje_ts)) / 3600.0, 1);
      v_dias           := v_horas_hoje / 24.0;
    END IF;

    SELECT COALESCE(sum(
             (l.prompt_tokens / 1000.0) * COALESCE(p.input_per_1k, 0)
           + (l.completion_tokens / 1000.0) * COALESCE(p.output_per_1k, 0)), 0)
      INTO v_custo_janela
      FROM public.ai_usage_log l
      LEFT JOIN public.ai_pricing p ON p.model = l.model
     WHERE l.model = ANY (c.modelos_maritaca)
       AND l.created_at >= (v_inicio_janela::timestamp AT TIME ZONE 'America/Sao_Paulo')
       AND l.created_at <= p_agora
       AND (v_horas_hoje IS NOT NULL OR l.created_at < v_hoje_ts);
    v_media := v_custo_janela / v_dias;
  END IF;

  IF v_saldo IS NOT NULL AND v_media > 0 THEN
    v_dias_restantes := round(GREATEST(v_saldo, 0) / v_media, 1);
  END IF;

  -- Erro real de falta de créditos.
  SELECT max(l.created_at), count(*) INTO v_ult_sem_cred, v_n_sem_cred
    FROM public.ai_usage_log l
   WHERE l.erro_codigo = 'ai_sem_creditos'
     AND l.created_at > p_agora - make_interval(hours => c.sem_creditos_horas)
     AND l.created_at <= p_agora;

  IF v_n_sem_cred > 0 THEN
    v_alertas := array_append(v_alertas, 'sem_creditos');
  END IF;
  IF v_saldo IS NOT NULL THEN
    IF v_saldo < c.urgente_reais OR v_dias_restantes < c.urgente_dias THEN
      v_alertas := array_append(v_alertas, 'urgente');
    ELSIF v_saldo < c.atencao_reais OR v_dias_restantes < c.atencao_dias THEN
      v_alertas := array_append(v_alertas, 'atencao');
    END IF;
  END IF;
  IF v_ultimo.id IS NULL
     OR p_agora - v_ultimo.registrado_em > make_interval(days => c.desatualizado_dias) THEN
    v_alertas := array_append(v_alertas, 'desatualizado');
  END IF;

  RETURN jsonb_build_object(
    'moeda',            v_moeda,
    'agora',            p_agora,
    'configurado',      v_base.id IS NOT NULL,
    'saldo_estimado',   round(v_saldo, 2),
    'saldo_base',       round(v_saldo_base, 2),
    'custo_desde_base', round(v_custo, 4),
    'base', CASE WHEN v_base.id IS NULL THEN NULL ELSE jsonb_build_object(
      'valor',          v_base.valor,
      'registrado_em',  v_base.registrado_em,
      'recargas',       v_recargas,
      'n_recargas',     v_n_recargas) END,
    'ultimo_registro', CASE WHEN v_ultimo.id IS NULL THEN NULL ELSE jsonb_build_object(
      'tipo',           v_ultimo.tipo,
      'valor',          v_ultimo.valor,
      'registrado_em',  v_ultimo.registrado_em,
      'registrado_por', v_ultimo.registrado_por,
      'nome',           v_ultimo_nome,
      'email',          v_ultimo_email,
      'observacao',     v_ultimo.observacao,
      'dias_atras',     v_dias_desde) END,
    'previsao', jsonb_build_object(
      'janela_dias',       c.janela_previsao_dias,
      'dias_considerados', COALESCE(v_dias_completos, 0),
      'horas_hoje',        round(v_horas_hoje, 1),
      'parcial',           COALESCE(v_dias_completos, 0) < c.janela_previsao_dias,
      'custo_janela',      round(COALESCE(v_custo_janela, 0), 4),
      'media_diaria',      round(v_media, 4),
      'dias_restantes',    v_dias_restantes),
    'sem_creditos', jsonb_build_object(
      'janela_horas',  c.sem_creditos_horas,
      'eventos',       v_n_sem_cred,
      'ultimo_evento', v_ult_sem_cred),
    'modelos_maritaca',           to_jsonb(c.modelos_maritaca),
    'modelos_maritaca_sem_preco', v_sem_preco,
    'limiares', jsonb_build_object(
      'urgente_reais',      c.urgente_reais,
      'urgente_dias',       c.urgente_dias,
      'atencao_reais',      c.atencao_reais,
      'atencao_dias',       c.atencao_dias,
      'desatualizado_dias', c.desatualizado_dias),
    'alertas', to_jsonb(v_alertas),
    'nivel',   COALESCE(v_alertas[1], 'ok')
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_ai_saldo_status()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT public.has_admin_scope('dashboard') THEN
    RAISE EXCEPTION 'forbidden: dashboard scope required';
  END IF;
  RETURN public.ai_saldo_status_em(now());
END;
$function$;

-- 'saldo_atual': o que o painel da Maritaca mostra agora (redefine a base).
-- 'recarga': crédito comprado depois do último saldo informado (soma à base).
-- Devolve o status já recalculado.
CREATE OR REPLACE FUNCTION public.registrar_ai_saldo(
  p_tipo       text,
  p_valor      numeric,
  p_observacao text DEFAULT NULL
)
 RETURNS jsonb
 LANGUAGE plpgsql
 VOLATILE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_obs text := NULLIF(btrim(COALESCE(p_observacao, '')), '');
BEGIN
  IF NOT public.has_admin_scope('dashboard') THEN
    RAISE EXCEPTION 'forbidden: dashboard scope required';
  END IF;

  IF p_tipo IS NULL OR p_tipo NOT IN ('saldo_atual', 'recarga') THEN
    RAISE EXCEPTION 'tipo inválido: %', p_tipo;
  END IF;
  IF p_valor IS NULL OR p_valor < 0 OR (p_tipo = 'recarga' AND p_valor = 0) THEN
    RAISE EXCEPTION 'valor inválido: %', p_valor;
  END IF;
  IF p_valor > 1000000 THEN
    RAISE EXCEPTION 'valor fora do esperado: %', p_valor;
  END IF;
  IF p_tipo = 'recarga'
     AND NOT EXISTS (SELECT 1 FROM public.ai_saldo_registros r WHERE r.tipo = 'saldo_atual') THEN
    RAISE EXCEPTION 'Informe o saldo atual antes de registrar uma recarga.';
  END IF;

  INSERT INTO public.ai_saldo_registros (tipo, valor, registrado_por, observacao)
  VALUES (p_tipo, round(p_valor, 2), auth.uid(), left(v_obs, 500));

  RETURN public.ai_saldo_status_em(now());
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.ai_saldo_status_em(timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ai_saldo_status_em(timestamptz) TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_ai_saldo_status() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.registrar_ai_saldo(text, numeric, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_ai_saldo_status() TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_ai_saldo(text, numeric, text) TO authenticated;

COMMIT;
