-- Darcy só para logados + cota diária de perguntas (29/09/2026).
-- Aplicar manualmente no SQL Editor do Supabase ANTES do deploy do backend que
-- chama estas funções (o backend recusa a pergunta com 503 se a reserva falhar).
-- Idempotente: pode ser reaplicada.
--
-- O que cria/altera:
--   1. ai_usage_log ganha user_id (auth.users.id de quem perguntou) e
--      pergunta_id (agrupa as chamadas ao LLM da mesma pergunta).
--   2. darcy_uso_diario: perguntas usadas por usuário por dia (dia no fuso
--      America/Sao_Paulo — renova à meia-noite de Brasília).
--   3. darcy_cota_concessoes: limite extra aprovado por um admin, vinculado ao
--      ticket de suporte "Mais perguntas no Darcy".
--   4. Funções do backend (service_role): reservar/estornar/consultar a cota e
--      somar o custo de IA do dia (teto global).
--   5. Funções do admin (is_ticket_admin): aprovar/recusar o pedido no ticket.
--   6. Dashboard: get_ai_cost_metrics passa a agrupar por dia de Brasília e
--      conta perguntas; get_darcy_uso_metrics mostra o uso das cotas.
--
-- Escrita nas tabelas novas: só via funções SECURITY DEFINER (ou service_role).
-- Leitura: o usuário vê só as próprias linhas; admin (dashboard/tickets) vê tudo.
--
-- REVERSÃO (rodar numa transação):
--   DROP FUNCTION IF EXISTS public.get_darcy_uso_metrics();
--   DROP FUNCTION IF EXISTS public.darcy_recusar_pedido(bigint, text);
--   DROP FUNCTION IF EXISTS public.darcy_aprovar_pedido(bigint, text, integer, text);
--   DROP FUNCTION IF EXISTS public.darcy_custo_ia_hoje();
--   DROP FUNCTION IF EXISTS public.darcy_estado_cota(uuid, integer);
--   DROP FUNCTION IF EXISTS public.darcy_estornar_pergunta(uuid, date);
--   DROP FUNCTION IF EXISTS public.darcy_reservar_pergunta(uuid, integer);
--   DROP FUNCTION IF EXISTS public.darcy_limite_efetivo(uuid, date, integer);
--   DROP FUNCTION IF EXISTS public.darcy_renova_em(date);
--   DROP FUNCTION IF EXISTS public.darcy_dia_brasilia(timestamptz);
--   DROP TABLE IF EXISTS public.darcy_cota_concessoes;
--   DROP TABLE IF EXISTS public.darcy_uso_diario;
--   ALTER TABLE public.ai_usage_log DROP COLUMN IF EXISTS pergunta_id;
--   ALTER TABLE public.ai_usage_log DROP COLUMN IF EXISTS user_id;
--   -- get_ai_cost_metrics: reaplicar a versão de latest_init_from_export.sql
--   -- (a nova só acrescenta chaves ao jsonb e troca o dia UTC pelo de Brasília).

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Rastreabilidade em ai_usage_log
-- ---------------------------------------------------------------------------

ALTER TABLE public.ai_usage_log ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.ai_usage_log ADD COLUMN IF NOT EXISTS pergunta_id uuid;

CREATE INDEX IF NOT EXISTS idx_ai_usage_user_id
  ON public.ai_usage_log (user_id, created_at) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ai_usage_pergunta_id
  ON public.ai_usage_log (pergunta_id) WHERE pergunta_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 2. Uso diário
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.darcy_uso_diario (
  user_id       uuid NOT NULL,
  dia           date NOT NULL,
  usadas        integer NOT NULL DEFAULT 0 CHECK (usadas >= 0),
  -- limite efetivo no momento da última reserva (histórico para o dashboard)
  limite        integer NOT NULL DEFAULT 0,
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT darcy_uso_diario_pkey PRIMARY KEY (user_id, dia)
);

CREATE INDEX IF NOT EXISTS idx_darcy_uso_diario_dia ON public.darcy_uso_diario (dia);

-- ---------------------------------------------------------------------------
-- 3. Concessões de limite extra
--    tipo 'extra':  soma `quantidade` perguntas por dia entre valida_de e valida_ate.
--    tipo 'limite': o limite diário passa a ser `quantidade` (se maior que o
--                   padrão) a partir de valida_de; valida_ate null = sem fim.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.darcy_cota_concessoes (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      uuid NOT NULL,
  tipo         text NOT NULL CHECK (tipo IN ('extra', 'limite')),
  quantidade   integer NOT NULL CHECK (quantidade BETWEEN 1 AND 1000),
  valida_de    date NOT NULL,
  valida_ate   date,
  motivo       text,
  ticket_id    bigint REFERENCES public.tickets(id) ON DELETE SET NULL,
  aprovado_por uuid NOT NULL,
  criado_em    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT darcy_concessao_periodo_ck CHECK (valida_ate IS NULL OR valida_ate >= valida_de),
  CONSTRAINT darcy_concessao_extra_com_fim_ck CHECK (tipo = 'limite' OR valida_ate IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_darcy_concessoes_user
  ON public.darcy_cota_concessoes (user_id, valida_de);
-- Um ticket gera no máximo uma concessão (evita aprovar duas vezes).
CREATE UNIQUE INDEX IF NOT EXISTS uq_darcy_concessoes_ticket
  ON public.darcy_cota_concessoes (ticket_id) WHERE ticket_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 4. RLS e grants das tabelas novas
-- ---------------------------------------------------------------------------

ALTER TABLE public.darcy_uso_diario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.darcy_cota_concessoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS darcy_uso_select_own_or_admin ON public.darcy_uso_diario;
CREATE POLICY darcy_uso_select_own_or_admin ON public.darcy_uso_diario
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.has_admin_scope('dashboard'));

DROP POLICY IF EXISTS darcy_concessoes_select_own_or_admin ON public.darcy_cota_concessoes;
CREATE POLICY darcy_concessoes_select_own_or_admin ON public.darcy_cota_concessoes
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.has_admin_scope('dashboard') OR public.is_ticket_admin());

-- Nenhuma policy de escrita: INSERT/UPDATE/DELETE só por função SECURITY
-- DEFINER ou service_role (que ignora RLS).
REVOKE ALL ON public.darcy_uso_diario FROM anon, authenticated;
REVOKE ALL ON public.darcy_cota_concessoes FROM anon, authenticated;
GRANT SELECT ON public.darcy_uso_diario TO authenticated;
GRANT SELECT ON public.darcy_cota_concessoes TO authenticated;

-- ---------------------------------------------------------------------------
-- 5. Funções de apoio
-- ---------------------------------------------------------------------------

-- Dia corrente (ou de p_em) no fuso de Brasília.
CREATE OR REPLACE FUNCTION public.darcy_dia_brasilia(p_em timestamptz DEFAULT now())
 RETURNS date
 LANGUAGE sql
 STABLE
AS $function$
  SELECT (p_em AT TIME ZONE 'America/Sao_Paulo')::date;
$function$;

-- Meia-noite de Brasília que encerra o dia p_dia.
CREATE OR REPLACE FUNCTION public.darcy_renova_em(p_dia date)
 RETURNS timestamptz
 LANGUAGE sql
 STABLE
AS $function$
  SELECT ((p_dia + 1)::timestamp AT TIME ZONE 'America/Sao_Paulo');
$function$;

-- Limite do dia = max(padrão, maior 'limite' vigente) + soma dos 'extra' vigentes.
CREATE OR REPLACE FUNCTION public.darcy_limite_efetivo(p_user_id uuid, p_dia date, p_limite_padrao integer)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT GREATEST(
           GREATEST(COALESCE(p_limite_padrao, 0), 0),
           COALESCE((SELECT max(c.quantidade) FROM public.darcy_cota_concessoes c
                      WHERE c.user_id = p_user_id AND c.tipo = 'limite'
                        AND c.valida_de <= p_dia
                        AND (c.valida_ate IS NULL OR c.valida_ate >= p_dia)), 0)
         )
       + COALESCE((SELECT sum(c.quantidade)::integer FROM public.darcy_cota_concessoes c
                    WHERE c.user_id = p_user_id AND c.tipo = 'extra'
                      AND c.valida_de <= p_dia AND c.valida_ate >= p_dia), 0);
$function$;

-- ---------------------------------------------------------------------------
-- 6. Funções do backend (service_role)
-- ---------------------------------------------------------------------------

-- Reserva ATÔMICA de uma pergunta: incrementa e checa o limite na MESMA
-- instrução (INSERT ... ON CONFLICT DO UPDATE ... WHERE usadas < limite). Duas
-- abas perguntando ao mesmo tempo serializam no lock da linha e a segunda
-- reavalia o WHERE com o valor já incrementado — não há como passar do limite.
CREATE OR REPLACE FUNCTION public.darcy_reservar_pergunta(p_user_id uuid, p_limite_padrao integer)
 RETURNS TABLE(permitido boolean, usadas integer, limite integer, dia date, renova_em timestamptz)
 LANGUAGE plpgsql
 VOLATILE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
#variable_conflict use_column
DECLARE
  v_dia    date := public.darcy_dia_brasilia(now());
  v_limite integer;
  v_usadas integer;
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'p_user_id é obrigatório';
  END IF;

  v_limite := public.darcy_limite_efetivo(p_user_id, v_dia, p_limite_padrao);

  IF v_limite > 0 THEN
    INSERT INTO public.darcy_uso_diario AS u (user_id, dia, usadas, limite)
    VALUES (p_user_id, v_dia, 1, v_limite)
    ON CONFLICT ON CONSTRAINT darcy_uso_diario_pkey DO UPDATE
       SET usadas = u.usadas + 1, limite = v_limite, atualizado_em = now()
     WHERE u.usadas < v_limite
    RETURNING u.usadas INTO v_usadas;
  END IF;

  IF v_usadas IS NOT NULL THEN
    RETURN QUERY SELECT true, v_usadas, v_limite, v_dia, public.darcy_renova_em(v_dia);
    RETURN;
  END IF;

  SELECT u.usadas INTO v_usadas
    FROM public.darcy_uso_diario u
   WHERE u.user_id = p_user_id AND u.dia = v_dia;

  RETURN QUERY SELECT false, COALESCE(v_usadas, 0), v_limite, v_dia, public.darcy_renova_em(v_dia);
END;
$function$;

-- Estorno: a IA falhou, a pergunta não conta. Recebe o dia da RESERVA (uma
-- pergunta feita às 23:59 que falha depois da meia-noite estorna o dia certo).
CREATE OR REPLACE FUNCTION public.darcy_estornar_pergunta(p_user_id uuid, p_dia date)
 RETURNS integer
 LANGUAGE sql
 VOLATILE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  UPDATE public.darcy_uso_diario u
     SET usadas = u.usadas - 1, atualizado_em = now()
   WHERE u.user_id = p_user_id AND u.dia = p_dia AND u.usadas > 0
  RETURNING u.usadas;
$function$;

-- Estado da cota sem consumir (rodinha ao abrir a página).
CREATE OR REPLACE FUNCTION public.darcy_estado_cota(p_user_id uuid, p_limite_padrao integer)
 RETURNS TABLE(usadas integer, limite integer, dia date, renova_em timestamptz)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE((SELECT u.usadas FROM public.darcy_uso_diario u
                    WHERE u.user_id = p_user_id AND u.dia = d.dia), 0),
         public.darcy_limite_efetivo(p_user_id, d.dia, p_limite_padrao),
         d.dia,
         public.darcy_renova_em(d.dia)
    FROM (SELECT public.darcy_dia_brasilia(now()) AS dia) d;
$function$;

-- Custo de IA do dia corrente (Brasília), mesmo cálculo do dashboard.
CREATE OR REPLACE FUNCTION public.darcy_custo_ia_hoje()
 RETURNS numeric
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE(round(sum(
           (l.prompt_tokens / 1000.0) * COALESCE(p.input_per_1k, 0)
         + (l.completion_tokens / 1000.0) * COALESCE(p.output_per_1k, 0)
         )::numeric, 4), 0)
    FROM public.ai_usage_log l
    LEFT JOIN public.ai_pricing p ON p.model = l.model
   WHERE l.created_at >= (public.darcy_dia_brasilia(now())::timestamp AT TIME ZONE 'America/Sao_Paulo');
$function$;

REVOKE EXECUTE ON FUNCTION public.darcy_limite_efetivo(uuid, date, integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.darcy_reservar_pergunta(uuid, integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.darcy_estornar_pergunta(uuid, date) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.darcy_estado_cota(uuid, integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.darcy_custo_ia_hoje() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.darcy_limite_efetivo(uuid, date, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.darcy_reservar_pergunta(uuid, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.darcy_estornar_pergunta(uuid, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.darcy_estado_cota(uuid, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.darcy_custo_ia_hoje() TO service_role;

-- ---------------------------------------------------------------------------
-- 7. Pedido de mais perguntas (ticket de suporte) — ações do admin
--    O ticket é criado pelo aluno no sistema de suporte existente com
--    metadata.tipo = 'darcy_mais_perguntas'. Aprovar cria a concessão vinculada
--    ao ticket, responde na conversa e resolve o ticket, tudo numa transação.
-- ---------------------------------------------------------------------------

-- Mensagem do suporte no ticket, com o mesmo efeito de "primeira resposta" de
-- ticket_add_message (sem o rate limit de 3s, que travaria a ação logo depois
-- de o admin ter escrito na conversa).
CREATE OR REPLACE FUNCTION public.darcy_responder_ticket(p_ticket_id bigint, p_texto text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.ticket_messages m
                  WHERE m.ticket_id = p_ticket_id AND m.author_role = 'tech') THEN
    INSERT INTO public.ticket_audit_log (ticket_id, actor_id, action, notes)
    VALUES (p_ticket_id, auth.uid(), 'message_added', 'Primeira resposta do suporte');
  END IF;

  INSERT INTO public.ticket_messages (ticket_id, author_id, author_role, content)
  VALUES (p_ticket_id, auth.uid(), 'tech', left(btrim(p_texto), 2000));
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.darcy_responder_ticket(bigint, text) FROM PUBLIC, anon, authenticated;

-- p_opcao: 'hoje'   → +p_quantidade só hoje;
--          'semana' → +p_quantidade por dia, de hoje até hoje+6;
--          'limite' → limite diário passa a p_quantidade, sem data de fim.
CREATE OR REPLACE FUNCTION public.darcy_aprovar_pedido(
  p_ticket_id  bigint,
  p_opcao      text,
  p_quantidade integer,
  p_resposta   text DEFAULT NULL
)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_ticket    public.tickets;
  v_hoje      date := public.darcy_dia_brasilia(now());
  v_tipo      text;
  v_ate       date;
  v_concessao public.darcy_cota_concessoes;
  v_texto     text;
BEGIN
  IF NOT public.is_ticket_admin() THEN
    RAISE EXCEPTION 'forbidden: admin role required';
  END IF;

  IF p_opcao NOT IN ('hoje', 'semana', 'limite') THEN
    RAISE EXCEPTION 'opção inválida: %', p_opcao;
  END IF;
  IF p_quantidade IS NULL OR p_quantidade < 1 OR p_quantidade > 1000 THEN
    RAISE EXCEPTION 'quantidade inválida: %', p_quantidade;
  END IF;

  SELECT t.* INTO v_ticket FROM public.tickets t WHERE t.id = p_ticket_id FOR UPDATE;
  IF v_ticket.id IS NULL THEN
    RAISE EXCEPTION 'ticket not found: %', p_ticket_id;
  END IF;
  IF COALESCE(v_ticket.metadata->>'tipo', '') <> 'darcy_mais_perguntas' THEN
    RAISE EXCEPTION 'Este chamado não é um pedido de mais perguntas no Darcy.';
  END IF;
  IF v_ticket.status = 'resolvido' THEN
    RAISE EXCEPTION 'Este chamado já foi resolvido.';
  END IF;
  IF EXISTS (SELECT 1 FROM public.darcy_cota_concessoes c WHERE c.ticket_id = p_ticket_id) THEN
    RAISE EXCEPTION 'Este pedido já foi aprovado.';
  END IF;

  IF p_opcao = 'limite' THEN
    v_tipo := 'limite'; v_ate := NULL;
  ELSIF p_opcao = 'semana' THEN
    v_tipo := 'extra'; v_ate := v_hoje + 6;
  ELSE
    v_tipo := 'extra'; v_ate := v_hoje;
  END IF;

  INSERT INTO public.darcy_cota_concessoes
    (user_id, tipo, quantidade, valida_de, valida_ate, motivo, ticket_id, aprovado_por)
  VALUES
    (v_ticket.created_by, v_tipo, p_quantidade, v_hoje, v_ate,
     left(COALESCE(v_ticket.metadata->>'motivo', v_ticket.description), 500),
     p_ticket_id, auth.uid())
  RETURNING * INTO v_concessao;

  v_texto := COALESCE(NULLIF(btrim(p_resposta), ''),
    CASE p_opcao
      WHEN 'hoje'   THEN format('Pedido aprovado! Você ganhou +%s perguntas no Darcy hoje.', p_quantidade)
      WHEN 'semana' THEN format('Pedido aprovado! Você ganhou +%s perguntas por dia no Darcy até %s.',
                                p_quantidade, to_char(v_ate, 'DD/MM'))
      ELSE format('Pedido aprovado! Seu limite no Darcy passou para %s perguntas por dia.', p_quantidade)
    END);
  PERFORM public.darcy_responder_ticket(p_ticket_id, v_texto);

  UPDATE public.tickets SET status = 'resolvido' WHERE id = p_ticket_id;

  RETURN to_jsonb(v_concessao);
END;
$function$;

CREATE OR REPLACE FUNCTION public.darcy_recusar_pedido(p_ticket_id bigint, p_resposta text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_ticket public.tickets;
BEGIN
  IF NOT public.is_ticket_admin() THEN
    RAISE EXCEPTION 'forbidden: admin role required';
  END IF;
  IF p_resposta IS NULL OR btrim(p_resposta) = '' THEN
    RAISE EXCEPTION 'Explique ao aluno o motivo da recusa.';
  END IF;

  SELECT t.* INTO v_ticket FROM public.tickets t WHERE t.id = p_ticket_id FOR UPDATE;
  IF v_ticket.id IS NULL THEN
    RAISE EXCEPTION 'ticket not found: %', p_ticket_id;
  END IF;
  IF COALESCE(v_ticket.metadata->>'tipo', '') <> 'darcy_mais_perguntas' THEN
    RAISE EXCEPTION 'Este chamado não é um pedido de mais perguntas no Darcy.';
  END IF;
  IF v_ticket.status = 'resolvido' THEN
    RAISE EXCEPTION 'Este chamado já foi resolvido.';
  END IF;

  PERFORM public.darcy_responder_ticket(p_ticket_id, p_resposta);
  UPDATE public.tickets SET status = 'resolvido' WHERE id = p_ticket_id;
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.darcy_aprovar_pedido(bigint, text, integer, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.darcy_recusar_pedido(bigint, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.darcy_aprovar_pedido(bigint, text, integer, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.darcy_recusar_pedido(bigint, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 8. Dashboard
-- ---------------------------------------------------------------------------

-- Mesma assinatura e chaves de antes, com três mudanças:
--   * por_dia agrupa pelo dia de Brasília (antes era o dia UTC: o que acontecia
--     depois das 21h caía no dia seguinte);
--   * total_perguntas: uma pergunta = mesmo pergunta_id, ou, nas linhas antigas
--     sem pergunta_id, mesmo (endpoint, created_at) — só nos endpoints que são
--     pergunta do aluno (chat/analyze). Linha sem pergunta_id de ferramenta
--     interna (buscar-materias, dificuldade do plano) entra no custo e em
--     total_requisicoes mas não é pergunta. As linhas antigas são aproximadas:
--     antes do pergunta_id, cada chamada ao modelo com horário próprio vira uma;
--   * por_endpoint, custo_hoje e sem_tokens (linhas sem tokens, que não custam).
CREATE OR REPLACE FUNCTION public.get_ai_cost_metrics(p_days integer DEFAULT 30)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_moeda        text;
  v_total_req    bigint;
  v_total_tokens bigint;
  v_custo_total  numeric;
  v_por_modelo   jsonb;
  v_por_dia      jsonb;
  v_por_endpoint jsonb;
  v_perguntas    bigint;
  v_sem_tokens   bigint;
  v_sem_preco    boolean;
BEGIN
  IF NOT public.has_admin_scope('dashboard') THEN
    RAISE EXCEPTION 'forbidden: dashboard scope required';
  END IF;

  SELECT COALESCE(max(currency), 'BRL') INTO v_moeda FROM public.ai_pricing;

  WITH r AS (
    SELECT l.endpoint, l.model, l.total_tokens, l.created_at,
           CASE
             WHEN l.pergunta_id IS NOT NULL THEN l.pergunta_id::text
             WHEN l.endpoint IN ('assistente-chat', 'planejamento-chat', 'chat-send',
                                 'analyze-sabia', 'analyze-sabia-stream')
               THEN l.endpoint || '|' || l.created_at::text
           END AS pergunta,  -- NULL = não é pergunta (count DISTINCT ignora)
           (l.prompt_tokens / 1000.0) * COALESCE(p.input_per_1k, 0)
         + (l.completion_tokens / 1000.0) * COALESCE(p.output_per_1k, 0) AS custo
      FROM public.ai_usage_log l
      LEFT JOIN public.ai_pricing p ON p.model = l.model
     WHERE l.created_at >= now() - (p_days || ' days')::interval
  )
  SELECT
    (SELECT count(*) FROM r),
    (SELECT COALESCE(sum(total_tokens), 0) FROM r),
    (SELECT COALESCE(round(sum(custo)::numeric, 4), 0) FROM r),
    (SELECT COALESCE(jsonb_object_agg(model, jsonb_build_object(
              'requisicoes', req, 'tokens', tok, 'custo', round(custo::numeric, 4)
            )) FILTER (WHERE model IS NOT NULL), '{}'::jsonb)
       FROM (SELECT model, count(*) AS req, sum(total_tokens) AS tok, sum(custo) AS custo
               FROM r GROUP BY model) m),
    (SELECT COALESCE(jsonb_agg(jsonb_build_object(
              'dia', d, 'custo', c, 'requisicoes', q_req, 'perguntas', q) ORDER BY d), '[]'::jsonb)
       FROM (SELECT (created_at AT TIME ZONE 'America/Sao_Paulo')::date AS d,
                    round(sum(custo)::numeric, 4) AS c,
                    count(*) AS q_req,
                    count(DISTINCT pergunta) AS q
               FROM r GROUP BY 1) s),
    (SELECT COALESCE(jsonb_object_agg(ep, jsonb_build_object(
              'requisicoes', q_req, 'perguntas', q, 'custo', round(c::numeric, 4))), '{}'::jsonb)
       FROM (SELECT COALESCE(endpoint, 'desconhecido') AS ep, count(*) AS q_req, sum(custo) AS c,
                    count(DISTINCT pergunta) AS q
               FROM r GROUP BY 1) e),
    (SELECT count(DISTINCT pergunta) FROM r),
    (SELECT count(*) FROM r WHERE total_tokens = 0)
  INTO v_total_req, v_total_tokens, v_custo_total, v_por_modelo, v_por_dia,
       v_por_endpoint, v_perguntas, v_sem_tokens;

  SELECT bool_or(input_per_1k = 0 AND output_per_1k = 0) INTO v_sem_preco
    FROM public.ai_pricing;

  RETURN jsonb_build_object(
    'moeda',                 v_moeda,
    'total_requisicoes',     COALESCE(v_total_req, 0),
    'total_perguntas',       COALESCE(v_perguntas, 0),
    'total_tokens',          COALESCE(v_total_tokens, 0),
    'custo_total',           COALESCE(v_custo_total, 0),
    'custo_hoje',            public.darcy_custo_ia_hoje(),
    'tokens_medios_por_req', CASE WHEN COALESCE(v_total_req, 0) > 0
                               THEN round(v_total_tokens::numeric / v_total_req, 0)
                               ELSE 0 END,
    'requisicoes_sem_tokens', COALESCE(v_sem_tokens, 0),
    'por_modelo',            COALESCE(v_por_modelo, '{}'::jsonb),
    'por_endpoint',          COALESCE(v_por_endpoint, '{}'::jsonb),
    'por_dia',               COALESCE(v_por_dia, '[]'::jsonb),
    'precos_nao_configurados', COALESCE(v_sem_preco, true)
  );
END;
$function$;

-- Uso das cotas do Darcy hoje (dia de Brasília).
CREATE OR REPLACE FUNCTION public.get_darcy_uso_metrics()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_hoje date := public.darcy_dia_brasilia(now());
  v_res  jsonb;
BEGIN
  IF NOT public.has_admin_scope('dashboard') THEN
    RAISE EXCEPTION 'forbidden: dashboard scope required';
  END IF;

  SELECT jsonb_build_object(
    'dia',                  v_hoje,
    'perguntas_hoje',       COALESCE((SELECT sum(u.usadas) FROM public.darcy_uso_diario u WHERE u.dia = v_hoje), 0),
    'usuarios_hoje',        (SELECT count(*) FROM public.darcy_uso_diario u WHERE u.dia = v_hoje AND u.usadas > 0),
    'usuarios_no_limite',   (SELECT count(*) FROM public.darcy_uso_diario u
                              WHERE u.dia = v_hoje AND u.limite > 0 AND u.usadas >= u.limite),
    'custo_hoje',           public.darcy_custo_ia_hoje(),
    'concessoes_vigentes',  (SELECT count(*) FROM public.darcy_cota_concessoes c
                              WHERE c.valida_de <= v_hoje AND (c.valida_ate IS NULL OR c.valida_ate >= v_hoje)),
    'pedidos_pendentes',    (SELECT count(*) FROM public.tickets t
                              WHERE t.metadata->>'tipo' = 'darcy_mais_perguntas' AND t.status <> 'resolvido'),
    'top_usuarios',         COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
               'nome', x.nome_completo, 'email', x.email, 'usadas', x.usadas, 'limite', x.limite)
             ORDER BY x.usadas DESC)
        FROM (SELECT u.usadas, u.limite, us.nome_completo, us.email
                FROM public.darcy_uso_diario u
                LEFT JOIN public.users us ON us.auth_id = u.user_id
               WHERE u.dia = v_hoje AND u.usadas > 0
               ORDER BY u.usadas DESC
               LIMIT 5) x), '[]'::jsonb)
  ) INTO v_res;

  RETURN v_res;
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.get_darcy_uso_metrics() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_darcy_uso_metrics() TO authenticated;

COMMIT;
