-- Chat de tickets (suporte) — tabela de mensagens, RPCs, Realtime e retenção.
-- Aplicar manualmente no SQL Editor do Supabase (idempotente).
--
-- Escrita: somente via RPC ticket_add_message (SECURITY DEFINER) — sem policy de INSERT.
-- Leitura: dono do ticket ou admin, via RPC get_ticket_messages (paginação) e
--          via RLS de SELECT (necessária para o Realtime entregar os eventos).

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Tabela de mensagens
--    Sem FK para users (padrão do repo: só a FK para tickets; author_name
--    resolvido por LEFT JOIN nas RPCs).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ticket_messages (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id   bigint NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  author_id   uuid NOT NULL,
  author_role text NOT NULL CHECK (author_role IN ('user', 'tech')),
  content     text NOT NULL CHECK (char_length(content) BETWEEN 1 AND 2000),
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Paginação por keyset: sempre filtramos por ticket_id e ordenamos por id.
CREATE INDEX IF NOT EXISTS ticket_messages_ticket_id_id_idx
  ON public.ticket_messages (ticket_id, id);

-- ticket_audit_log tem em produção um CHECK em action (ticket_audit_log_action_check)
-- que NÃO aparece no export do schema — sem este patch, a action nova
-- 'message_added' (primeira resposta do suporte) estoura o constraint e derruba
-- a RPC ticket_add_message inteira no caminho tech. Recria com a lista completa.
ALTER TABLE public.ticket_audit_log
  DROP CONSTRAINT IF EXISTS ticket_audit_log_action_check;
ALTER TABLE public.ticket_audit_log
  ADD CONSTRAINT ticket_audit_log_action_check CHECK (action IN (
    'created', 'status_changed', 'assigned', 'priority_changed',
    'category_changed', 'note_updated', 'closed', 'message_added'
  ));

-- ---------------------------------------------------------------------------
-- 2. RLS
--    Apenas SELECT: dono do ticket ou admin. NENHUMA policy de INSERT/UPDATE/
--    DELETE — toda escrita passa pela RPC ticket_add_message (SECURITY DEFINER),
--    que valida permissão, conteúdo, status e rate limit no corpo.
-- ---------------------------------------------------------------------------

ALTER TABLE public.ticket_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ticket_messages_select_own_or_admin ON public.ticket_messages;
CREATE POLICY ticket_messages_select_own_or_admin ON public.ticket_messages
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.tickets t
      WHERE t.id = ticket_id
        AND (t.created_by = auth.uid() OR public.is_ticket_admin())
    )
  );

-- ---------------------------------------------------------------------------
-- 3. Grants da tabela
--    GRANT SELECT para authenticated é necessário para o Realtime entregar os
--    eventos de INSERT respeitando a RLS acima. anon não enxerga nada.
-- ---------------------------------------------------------------------------

REVOKE ALL ON public.ticket_messages FROM anon;
GRANT SELECT ON public.ticket_messages TO authenticated;

-- ---------------------------------------------------------------------------
-- 4. RPCs
-- ---------------------------------------------------------------------------

-- Lista mensagens de um ticket com paginação por keyset.
--   - p_after_id:  mensagens com id > p_after_id, em ordem ASC (buscar novas);
--   - p_before_id: as p_limit mais RECENTES com id < p_before_id (ou tudo se
--     null), retornadas em ordem ASC (carregar histórico para trás).
CREATE OR REPLACE FUNCTION public.get_ticket_messages(
  p_ticket_id bigint,
  p_before_id bigint DEFAULT NULL,
  p_after_id  bigint DEFAULT NULL,
  p_limit     int DEFAULT 30
)
 RETURNS TABLE(
   id          bigint,
   ticket_id   bigint,
   author_id   uuid,
   author_role text,
   content     text,
   created_at  timestamptz,
   author_name text
 )
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_limit int := LEAST(GREATEST(COALESCE(p_limit, 30), 1), 100);
BEGIN
  -- Acesso: dono do ticket ou admin.
  IF NOT EXISTS (
    SELECT 1 FROM public.tickets t
    WHERE t.id = p_ticket_id
      AND (t.created_by = auth.uid() OR public.is_ticket_admin())
  ) THEN
    RAISE EXCEPTION 'ticket not found or access denied';
  END IF;

  IF p_after_id IS NOT NULL THEN
    RETURN QUERY
    SELECT m.id, m.ticket_id, m.author_id, m.author_role, m.content, m.created_at,
           u.nome_completo
    FROM public.ticket_messages m
    LEFT JOIN public.users u ON u.auth_id = m.author_id
    WHERE m.ticket_id = p_ticket_id
      AND m.id > p_after_id
    ORDER BY m.id ASC
    LIMIT v_limit;
  ELSE
    -- Pega as v_limit mais recentes (DESC LIMIT) e devolve em ordem ASC.
    RETURN QUERY
    SELECT sub.id, sub.ticket_id, sub.author_id, sub.author_role, sub.content,
           sub.created_at, u.nome_completo
    FROM (
      SELECT m.id, m.ticket_id, m.author_id, m.author_role, m.content, m.created_at
      FROM public.ticket_messages m
      WHERE m.ticket_id = p_ticket_id
        AND (p_before_id IS NULL OR m.id < p_before_id)
      ORDER BY m.id DESC
      LIMIT v_limit
    ) sub
    LEFT JOIN public.users u ON u.auth_id = sub.author_id
    ORDER BY sub.id ASC;
  END IF;
END;
$function$;

-- Insere uma mensagem no chat do ticket e aplica os efeitos colaterais.
-- Retorna a mensagem inserida como jsonb, no mesmo shape de get_ticket_messages.
CREATE OR REPLACE FUNCTION public.ticket_add_message(p_ticket_id bigint, p_content text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_ticket      public.tickets;
  v_content     text := btrim(COALESCE(p_content, ''));
  v_role        text;
  v_last_at     timestamptz;
  v_msg         public.ticket_messages;
  v_author_name text;
BEGIN
  IF char_length(v_content) < 1 THEN
    RAISE EXCEPTION 'A mensagem não pode ficar vazia.';
  END IF;

  IF char_length(v_content) > 2000 THEN
    RAISE EXCEPTION 'A mensagem pode ter no máximo 2000 caracteres.';
  END IF;

  -- FOR UPDATE serializa envios concorrentes no mesmo ticket: o rate limit, a
  -- checagem de status e o audit de "primeira resposta" leem estado fresco.
  SELECT t.* INTO v_ticket FROM public.tickets t WHERE t.id = p_ticket_id FOR UPDATE;

  IF v_ticket.id IS NULL THEN
    RAISE EXCEPTION 'ticket not found: %', p_ticket_id;
  END IF;

  -- Acesso: dono do ticket ou admin.
  IF v_ticket.created_by <> auth.uid() AND NOT public.is_ticket_admin() THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  IF v_ticket.status = 'resolvido' THEN
    RAISE EXCEPTION 'Este chamado já foi resolvido. Abra um novo chamado se precisar.';
  END IF;

  -- Rate limit: no máximo 1 mensagem a cada 3 segundos por autor no ticket.
  SELECT max(m.created_at) INTO v_last_at
  FROM public.ticket_messages m
  WHERE m.ticket_id = p_ticket_id
    AND m.author_id = auth.uid();

  IF v_last_at IS NOT NULL AND v_last_at > now() - interval '3 seconds' THEN
    RAISE EXCEPTION 'Aguarde alguns segundos antes de enviar outra mensagem.';
  END IF;

  -- O dono do ticket fala como 'user' mesmo que também seja admin.
  IF v_ticket.created_by = auth.uid() THEN
    v_role := 'user';
  ELSE
    v_role := 'tech';
  END IF;

  -- Primeira resposta do suporte neste ticket → registra no audit log.
  -- (checado ANTES do insert, para a própria mensagem não contar)
  IF v_role = 'tech' AND NOT EXISTS (
    SELECT 1 FROM public.ticket_messages m
    WHERE m.ticket_id = p_ticket_id
      AND m.author_role = 'tech'
  ) THEN
    INSERT INTO public.ticket_audit_log (ticket_id, actor_id, action, notes)
    VALUES (p_ticket_id, auth.uid(), 'message_added', 'Primeira resposta do suporte');
  END IF;

  INSERT INTO public.ticket_messages (ticket_id, author_id, author_role, content)
  VALUES (p_ticket_id, auth.uid(), v_role, v_content)
  RETURNING * INTO v_msg;

  -- Efeitos colaterais de status: UPDATE direto na tabela — a trigger
  -- trg_tickets_on_update já audita a mudança de status.
  IF v_role = 'user' AND v_ticket.status = 'aguardando_info' THEN
    UPDATE public.tickets SET status = 'em_andamento' WHERE id = p_ticket_id;
  ELSIF v_role = 'tech' AND v_ticket.status = 'aberto' THEN
    UPDATE public.tickets SET status = 'em_andamento' WHERE id = p_ticket_id;
  END IF;

  SELECT u.nome_completo INTO v_author_name
  FROM public.users u
  WHERE u.auth_id = v_msg.author_id;

  RETURN jsonb_build_object(
    'id',          v_msg.id,
    'ticket_id',   v_msg.ticket_id,
    'author_id',   v_msg.author_id,
    'author_role', v_msg.author_role,
    'content',     v_msg.content,
    'created_at',  v_msg.created_at,
    'author_name', v_author_name
  );
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.get_ticket_messages(bigint, bigint, bigint, int) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_ticket_messages(bigint, bigint, bigint, int) FROM anon;
GRANT EXECUTE ON FUNCTION public.get_ticket_messages(bigint, bigint, bigint, int) TO authenticated;

REVOKE EXECUTE ON FUNCTION public.ticket_add_message(bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ticket_add_message(bigint, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.ticket_add_message(bigint, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 5. Realtime
--    Adiciona ticket_messages à publication supabase_realtime (só se ainda não
--    estiver). O Realtime precisa estar habilitado no projeto (Dashboard →
--    Database → Replication) e entrega os eventos respeitando a RLS de SELECT.
-- ---------------------------------------------------------------------------

DO $realtime$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'ticket_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.ticket_messages;
  END IF;
END;
$realtime$;

-- ---------------------------------------------------------------------------
-- 6. Retenção via pg_cron
--    Só agenda se a extensão pg_cron estiver instalada. cron.schedule com um
--    nome de job já existente sobrescreve o agendamento — ou seja, o bloco é
--    idempotente.
-- ---------------------------------------------------------------------------

DO $cron$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN

    -- Diário às 03:00 — auto-resolve tickets em 'aguardando_info' cujo usuário
    -- não respondeu em 14 dias (a trigger audita a mudança com actor null).
    PERFORM cron.schedule(
      'tickets_auto_resolver_aguardando',
      '0 3 * * *',
      $cron1$
        UPDATE public.tickets
           SET status = 'resolvido'
         WHERE status = 'aguardando_info'
           AND updated_at < now() - interval '14 days';
      $cron1$
    );

    -- Semanal, domingo às 04:00 — apaga conversas de tickets resolvidos há
    -- mais de 6 meses (a conversa expira, o audit_log preserva a história).
    PERFORM cron.schedule(
      'ticket_messages_purge_resolvidos',
      '0 4 * * 0',
      $cron2$
        DELETE FROM public.ticket_messages
         WHERE ticket_id IN (
           SELECT id FROM public.tickets
            WHERE status = 'resolvido'
              AND resolved_at < now() - interval '6 months'
         );
      $cron2$
    );

  ELSE
    RAISE NOTICE 'pg_cron não instalado — habilite em Dashboard → Database → Extensions e reaplique esta migration para agendar a retenção.';
  END IF;
END;
$cron$;

COMMIT;
