name: Run web scraper

on:
  push:
    branches: [scraping]
  workflow_dispatch:

jobs:
     build:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout Repository
            uses: actions/checkout@v3
          
          - name: Setup Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.9'

          - name: Upgrade pip and install Cython
            run: |
              python -m pip install --upgrade pip
              pip install Cython

          - name: Install dependencies
            run: |
              pip install wheel
              pip install --no-build-isolation -r scraping/requirements.txt

          - name: Execute Script
            run: |
              python scraping/scrapin_atual.py
              python scraping/scraping_courses.py
              python scraping/scraping_cursos.py
              python scraping/scraping_ementa.py
              python scraping/scraping_id_departamentos.py
              python scraping/scraping_sigaa.py
              python scraping/scraping_turmas_por_depto.py
              python scraping/scraping.py
              python scraping/script_json_para_txt.py
              python scraping/sigaa_scraper.py
              python scraping/temp_parser.py

          - name: Commit Changes
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: "[CI] Scraping dos cursos atualizados com sucesso!"
              file_pattern: "dados/estruturas-curriculares/*.json"
